import { z } from "zod";
export declare const hoursSchema: z.ZodObject<{
    timezone: z.ZodOptional<z.ZodString>;
    summary: z.ZodOptional<z.ZodString>;
    weekly: z.ZodDefault<z.ZodObject<{
        monday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        tuesday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        wednesday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        thursday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        friday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        saturday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        sunday: z.ZodOptional<z.ZodObject<{
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    holidayHours: z.ZodDefault<z.ZodArray<z.ZodObject<{
        date: z.ZodString;
        name: z.ZodOptional<z.ZodString>;
        isClosed: z.ZodDefault<z.ZodBoolean>;
        ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
            opens: z.ZodString;
            closes: z.ZodString;
            label: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
        note: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
}, z.core.$strict>;
export declare const businessSchema: z.ZodObject<{
    name: z.ZodString;
    legalName: z.ZodOptional<z.ZodString>;
    tagline: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    industry: z.ZodOptional<z.ZodString>;
    entityType: z.ZodOptional<z.ZodString>;
    foundedYear: z.ZodOptional<z.ZodNumber>;
    yearsInBusiness: z.ZodOptional<z.ZodNumber>;
    languages: z.ZodDefault<z.ZodArray<z.ZodString>>;
    timezone: z.ZodOptional<z.ZodString>;
    keywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strict>;
export declare const brandSchema: z.ZodObject<{
    logo: z.ZodOptional<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    icon: z.ZodOptional<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    colors: z.ZodDefault<z.ZodObject<{
        primary: z.ZodOptional<z.ZodString>;
        secondary: z.ZodOptional<z.ZodString>;
        accent: z.ZodOptional<z.ZodString>;
        background: z.ZodOptional<z.ZodString>;
        foreground: z.ZodOptional<z.ZodString>;
        muted: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    typography: z.ZodDefault<z.ZodObject<{
        headingFont: z.ZodOptional<z.ZodString>;
        bodyFont: z.ZodOptional<z.ZodString>;
        monospaceFont: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    voice: z.ZodPrefault<z.ZodObject<{
        tone: z.ZodOptional<z.ZodString>;
        personality: z.ZodDefault<z.ZodArray<z.ZodString>>;
        writingGuidelines: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>;
    assets: z.ZodDefault<z.ZodArray<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
}, z.core.$strict>;
export declare const contactSchema: z.ZodObject<{
    email: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    smsPhone: z.ZodOptional<z.ZodString>;
    fax: z.ZodOptional<z.ZodString>;
    website: z.ZodOptional<z.ZodString>;
    contactName: z.ZodOptional<z.ZodString>;
    preferredContactMethod: z.ZodOptional<z.ZodEnum<{
        email: "email";
        phone: "phone";
        sms: "sms";
        form: "form";
        appointment: "appointment";
    }>>;
    address: z.ZodOptional<z.ZodObject<{
        street1: z.ZodOptional<z.ZodString>;
        street2: z.ZodOptional<z.ZodString>;
        city: z.ZodOptional<z.ZodString>;
        region: z.ZodOptional<z.ZodString>;
        postalCode: z.ZodOptional<z.ZodString>;
        country: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    mapUrl: z.ZodOptional<z.ZodString>;
    mapEmbedUrl: z.ZodOptional<z.ZodString>;
    emergencyPhone: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const locationSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    address: z.ZodOptional<z.ZodObject<{
        street1: z.ZodOptional<z.ZodString>;
        street2: z.ZodOptional<z.ZodString>;
        city: z.ZodOptional<z.ZodString>;
        region: z.ZodOptional<z.ZodString>;
        postalCode: z.ZodOptional<z.ZodString>;
        country: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    contact: z.ZodDefault<z.ZodObject<{
        email: z.ZodOptional<z.ZodString>;
        phone: z.ZodOptional<z.ZodString>;
        smsPhone: z.ZodOptional<z.ZodString>;
        fax: z.ZodOptional<z.ZodString>;
        website: z.ZodOptional<z.ZodString>;
        contactName: z.ZodOptional<z.ZodString>;
        preferredContactMethod: z.ZodOptional<z.ZodEnum<{
            email: "email";
            phone: "phone";
            sms: "sms";
            form: "form";
            appointment: "appointment";
        }>>;
        address: z.ZodOptional<z.ZodObject<{
            street1: z.ZodOptional<z.ZodString>;
            street2: z.ZodOptional<z.ZodString>;
            city: z.ZodOptional<z.ZodString>;
            region: z.ZodOptional<z.ZodString>;
            postalCode: z.ZodOptional<z.ZodString>;
            country: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        mapUrl: z.ZodOptional<z.ZodString>;
        mapEmbedUrl: z.ZodOptional<z.ZodString>;
        emergencyPhone: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    hours: z.ZodOptional<z.ZodObject<{
        timezone: z.ZodOptional<z.ZodString>;
        summary: z.ZodOptional<z.ZodString>;
        weekly: z.ZodDefault<z.ZodObject<{
            monday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            tuesday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            wednesday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            thursday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            friday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            saturday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            sunday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        holidayHours: z.ZodDefault<z.ZodArray<z.ZodObject<{
            date: z.ZodString;
            name: z.ZodOptional<z.ZodString>;
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>;
    geo: z.ZodOptional<z.ZodObject<{
        latitude: z.ZodNumber;
        longitude: z.ZodNumber;
    }, z.core.$strict>>;
    serviceArea: z.ZodDefault<z.ZodArray<z.ZodString>>;
    amenities: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strict>;
export declare const heroSchema: z.ZodObject<{
    eyebrow: z.ZodOptional<z.ZodString>;
    headline: z.ZodString;
    subheadline: z.ZodOptional<z.ZodString>;
    body: z.ZodOptional<z.ZodString>;
    primaryCta: z.ZodOptional<z.ZodObject<{
        label: z.ZodString;
        url: z.ZodString;
        ariaLabel: z.ZodOptional<z.ZodString>;
        target: z.ZodDefault<z.ZodEnum<{
            self: "self";
            blank: "blank";
        }>>;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            tertiary: "tertiary";
            link: "link";
            button: "button";
        }>>;
    }, z.core.$strict>>;
    secondaryCta: z.ZodOptional<z.ZodObject<{
        label: z.ZodString;
        url: z.ZodString;
        ariaLabel: z.ZodOptional<z.ZodString>;
        target: z.ZodDefault<z.ZodEnum<{
            self: "self";
            blank: "blank";
        }>>;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            tertiary: "tertiary";
            link: "link";
            button: "button";
        }>>;
    }, z.core.$strict>>;
    image: z.ZodOptional<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    video: z.ZodOptional<z.ZodObject<{
        title: z.ZodString;
        url: z.ZodString;
        provider: z.ZodDefault<z.ZodEnum<{
            youtube: "youtube";
            vimeo: "vimeo";
            "self-hosted": "self-hosted";
            other: "other";
        }>>;
        thumbnail: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        transcript: z.ZodOptional<z.ZodString>;
        duration: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    trustSignals: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strict>;
export declare const contentSectionSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    subtitle: z.ZodOptional<z.ZodString>;
    body: z.ZodOptional<z.ZodString>;
    blocks: z.ZodDefault<z.ZodArray<z.ZodObject<{
        heading: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        links: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>>;
    images: z.ZodDefault<z.ZodArray<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
    cta: z.ZodOptional<z.ZodObject<{
        label: z.ZodString;
        url: z.ZodString;
        ariaLabel: z.ZodOptional<z.ZodString>;
        target: z.ZodDefault<z.ZodEnum<{
            self: "self";
            blank: "blank";
        }>>;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            tertiary: "tertiary";
            link: "link";
            button: "button";
        }>>;
    }, z.core.$strict>>;
}, z.core.$strict>;
export declare const serviceSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    shortDescription: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    category: z.ZodOptional<z.ZodString>;
    price: z.ZodOptional<z.ZodString>;
    duration: z.ZodOptional<z.ZodString>;
    image: z.ZodOptional<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    features: z.ZodDefault<z.ZodArray<z.ZodString>>;
    serviceAreas: z.ZodDefault<z.ZodArray<z.ZodString>>;
    cta: z.ZodOptional<z.ZodObject<{
        label: z.ZodString;
        url: z.ZodString;
        ariaLabel: z.ZodOptional<z.ZodString>;
        target: z.ZodDefault<z.ZodEnum<{
            self: "self";
            blank: "blank";
        }>>;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            tertiary: "tertiary";
            link: "link";
            button: "button";
        }>>;
    }, z.core.$strict>>;
}, z.core.$strict>;
export declare const productSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    category: z.ZodOptional<z.ZodString>;
    sku: z.ZodOptional<z.ZodString>;
    price: z.ZodOptional<z.ZodString>;
    images: z.ZodDefault<z.ZodArray<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
    features: z.ZodDefault<z.ZodArray<z.ZodString>>;
    available: z.ZodDefault<z.ZodBoolean>;
    cta: z.ZodOptional<z.ZodObject<{
        label: z.ZodString;
        url: z.ZodString;
        ariaLabel: z.ZodOptional<z.ZodString>;
        target: z.ZodDefault<z.ZodEnum<{
            self: "self";
            blank: "blank";
        }>>;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            tertiary: "tertiary";
            link: "link";
            button: "button";
        }>>;
    }, z.core.$strict>>;
}, z.core.$strict>;
export declare const pricingSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    currency: z.ZodOptional<z.ZodString>;
    plans: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        price: z.ZodString;
        period: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        features: z.ZodDefault<z.ZodArray<z.ZodString>>;
        highlighted: z.ZodDefault<z.ZodBoolean>;
        cta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
    notes: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strict>;
export declare const faqItemSchema: z.ZodObject<{
    question: z.ZodString;
    answer: z.ZodString;
    category: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const reviewSchema: z.ZodObject<{
    author: z.ZodString;
    quote: z.ZodString;
    rating: z.ZodOptional<z.ZodNumber>;
    source: z.ZodOptional<z.ZodString>;
    date: z.ZodOptional<z.ZodString>;
    url: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const teamMemberSchema: z.ZodObject<{
    name: z.ZodString;
    role: z.ZodOptional<z.ZodString>;
    bio: z.ZodOptional<z.ZodString>;
    photo: z.ZodOptional<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    credentials: z.ZodDefault<z.ZodArray<z.ZodString>>;
    socialLinks: z.ZodDefault<z.ZodArray<z.ZodObject<{
        platform: z.ZodString;
        url: z.ZodString;
        handle: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
}, z.core.$strict>;
export declare const careersSchema: z.ZodObject<{
    intro: z.ZodOptional<z.ZodString>;
    benefits: z.ZodDefault<z.ZodArray<z.ZodString>>;
    openings: z.ZodDefault<z.ZodArray<z.ZodObject<{
        title: z.ZodString;
        location: z.ZodOptional<z.ZodString>;
        type: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        requirements: z.ZodDefault<z.ZodArray<z.ZodString>>;
        applyUrl: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
}, z.core.$strict>;
export declare const formSchema: z.ZodObject<{
    id: z.ZodString;
    title: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    submitLabel: z.ZodDefault<z.ZodString>;
    fields: z.ZodDefault<z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        label: z.ZodString;
        type: z.ZodDefault<z.ZodEnum<{
            number: "number";
            date: "date";
            file: "file";
            email: "email";
            phone: "phone";
            text: "text";
            textarea: "textarea";
            select: "select";
            checkbox: "checkbox";
            radio: "radio";
            time: "time";
        }>>;
        required: z.ZodDefault<z.ZodBoolean>;
        placeholder: z.ZodOptional<z.ZodString>;
        options: z.ZodDefault<z.ZodArray<z.ZodString>>;
        helpText: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    successMessage: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const appointmentsSchema: z.ZodObject<{
    enabled: z.ZodDefault<z.ZodBoolean>;
    bookingUrl: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    appointmentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
    leadTime: z.ZodOptional<z.ZodString>;
    cancellationPolicy: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const reservationsSchema: z.ZodObject<{
    enabled: z.ZodDefault<z.ZodBoolean>;
    reservationUrl: z.ZodOptional<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
    partySizeMin: z.ZodOptional<z.ZodNumber>;
    partySizeMax: z.ZodOptional<z.ZodNumber>;
    policy: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const menuSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    sections: z.ZodDefault<z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        items: z.ZodDefault<z.ZodArray<z.ZodObject<{
            name: z.ZodString;
            description: z.ZodOptional<z.ZodString>;
            price: z.ZodOptional<z.ZodString>;
            image: z.ZodOptional<z.ZodObject<{
                src: z.ZodString;
                alt: z.ZodDefault<z.ZodString>;
                caption: z.ZodOptional<z.ZodString>;
                width: z.ZodOptional<z.ZodNumber>;
                height: z.ZodOptional<z.ZodNumber>;
                focalPoint: z.ZodOptional<z.ZodObject<{
                    x: z.ZodNumber;
                    y: z.ZodNumber;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
            allergens: z.ZodDefault<z.ZodArray<z.ZodString>>;
            available: z.ZodDefault<z.ZodBoolean>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>>;
}, z.core.$strict>;
export declare const insuranceSchema: z.ZodObject<{
    accepted: z.ZodDefault<z.ZodArray<z.ZodString>>;
    notAccepted: z.ZodDefault<z.ZodArray<z.ZodString>>;
    notes: z.ZodOptional<z.ZodString>;
    verificationUrl: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const promotionSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    title: z.ZodString;
    summary: z.ZodOptional<z.ZodString>;
    body: z.ZodOptional<z.ZodString>;
    date: z.ZodOptional<z.ZodString>;
    image: z.ZodOptional<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    url: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    code: z.ZodOptional<z.ZodString>;
    startsAt: z.ZodOptional<z.ZodString>;
    endsAt: z.ZodOptional<z.ZodString>;
    terms: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const seoSchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    keywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
    canonicalUrl: z.ZodOptional<z.ZodString>;
    noIndex: z.ZodDefault<z.ZodBoolean>;
    openGraph: z.ZodDefault<z.ZodObject<{
        title: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        type: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    structuredData: z.ZodDefault<z.ZodArray<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
}, z.core.$strict>;
export declare const analyticsSchema: z.ZodObject<{
    googleAnalyticsId: z.ZodOptional<z.ZodString>;
    googleTagManagerId: z.ZodOptional<z.ZodString>;
    metaPixelId: z.ZodOptional<z.ZodString>;
    events: z.ZodDefault<z.ZodArray<z.ZodString>>;
    consentRequired: z.ZodDefault<z.ZodBoolean>;
}, z.core.$strict>;
export declare const legalSchema: z.ZodObject<{
    privacyPolicyUrl: z.ZodOptional<z.ZodString>;
    termsUrl: z.ZodOptional<z.ZodString>;
    cookiePolicyUrl: z.ZodOptional<z.ZodString>;
    licenses: z.ZodDefault<z.ZodArray<z.ZodString>>;
    disclaimers: z.ZodDefault<z.ZodArray<z.ZodString>>;
    copyright: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
export declare const accessibilitySchema: z.ZodObject<{
    statementUrl: z.ZodOptional<z.ZodString>;
    contactEmail: z.ZodOptional<z.ZodString>;
    contactPhone: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
    standards: z.ZodDefault<z.ZodArray<z.ZodString>>;
}, z.core.$strict>;
export declare const templateSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    name: z.ZodOptional<z.ZodString>;
    variant: z.ZodOptional<z.ZodString>;
    layout: z.ZodOptional<z.ZodString>;
    hiddenSections: z.ZodDefault<z.ZodArray<z.ZodString>>;
    sectionOrder: z.ZodDefault<z.ZodArray<z.ZodString>>;
    options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, z.core.$strict>;
export declare const themeSchema: z.ZodObject<{
    mode: z.ZodDefault<z.ZodEnum<{
        light: "light";
        dark: "dark";
        system: "system";
    }>>;
    radius: z.ZodOptional<z.ZodString>;
    spacing: z.ZodOptional<z.ZodString>;
    colors: z.ZodDefault<z.ZodDefault<z.ZodObject<{
        primary: z.ZodOptional<z.ZodString>;
        secondary: z.ZodOptional<z.ZodString>;
        accent: z.ZodOptional<z.ZodString>;
        background: z.ZodOptional<z.ZodString>;
        foreground: z.ZodOptional<z.ZodString>;
        muted: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    customCss: z.ZodOptional<z.ZodString>;
}, z.core.$strict>;
declare const universalActionSchema: z.ZodObject<{
    label: z.ZodString;
    href: z.ZodString;
    variant: z.ZodDefault<z.ZodEnum<{
        primary: "primary";
        secondary: "secondary";
        text: "text";
    }>>;
}, z.core.$strip>;
export declare const universalSiteSchema: z.ZodObject<{
    schemaVersion: z.ZodNumber;
    slug: z.ZodString;
    vertical: z.ZodString;
    theme: z.ZodObject<{
        name: z.ZodString;
        palette: z.ZodEnum<{
            clinic: "clinic";
            trade: "trade";
            hospitality: "hospitality";
            professional: "professional";
        }>;
        mode: z.ZodDefault<z.ZodEnum<{
            light: "light";
            dark: "dark";
        }>>;
        radius: z.ZodDefault<z.ZodEnum<{
            soft: "soft";
            rounded: "rounded";
            crisp: "crisp";
        }>>;
    }, z.core.$strip>;
    seo: z.ZodObject<{
        title: z.ZodString;
        description: z.ZodString;
        canonicalPath: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    business: z.ZodObject<{
        name: z.ZodString;
        type: z.ZodString;
        tagline: z.ZodString;
        description: z.ZodString;
        phone: z.ZodString;
        email: z.ZodOptional<z.ZodString>;
        address: z.ZodObject<{
            street: z.ZodString;
            city: z.ZodString;
            region: z.ZodString;
            postalCode: z.ZodString;
            country: z.ZodDefault<z.ZodString>;
        }, z.core.$strip>;
        areaServed: z.ZodDefault<z.ZodArray<z.ZodString>>;
        hours: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            value: z.ZodString;
        }, z.core.$strip>>>;
        credentials: z.ZodDefault<z.ZodArray<z.ZodString>>;
        social: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    navigation: z.ZodDefault<z.ZodArray<z.ZodObject<{
        label: z.ZodString;
        href: z.ZodString;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            text: "text";
        }>>;
    }, z.core.$strip>>>;
    hero: z.ZodObject<{
        eyebrow: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodString;
        primaryCta: z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>;
        secondaryCta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>>;
        mediaAlt: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    sections: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<{
            services: "services";
            proof: "proof";
            process: "process";
            testimonials: "testimonials";
            faq: "faq";
            content: "content";
        }>;
        eyebrow: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        items: z.ZodDefault<z.ZodArray<z.ZodObject<{
            title: z.ZodString;
            description: z.ZodString;
        }, z.core.$strip>>>;
        stats: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            value: z.ZodString;
        }, z.core.$strip>>>;
        steps: z.ZodDefault<z.ZodArray<z.ZodObject<{
            title: z.ZodString;
            description: z.ZodString;
        }, z.core.$strip>>>;
        testimonials: z.ZodDefault<z.ZodArray<z.ZodObject<{
            quote: z.ZodString;
            name: z.ZodString;
            context: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>>;
        questions: z.ZodDefault<z.ZodArray<z.ZodObject<{
            question: z.ZodString;
            answer: z.ZodString;
        }, z.core.$strip>>>;
        actions: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
    ctas: z.ZodOptional<z.ZodObject<{
        final: z.ZodObject<{
            title: z.ZodString;
            summary: z.ZodString;
            actions: z.ZodArray<z.ZodObject<{
                label: z.ZodString;
                href: z.ZodString;
                variant: z.ZodDefault<z.ZodEnum<{
                    primary: "primary";
                    secondary: "secondary";
                    text: "text";
                }>>;
            }, z.core.$strip>>;
        }, z.core.$strip>;
    }, z.core.$strip>>;
    pages: z.ZodArray<z.ZodObject<{
        path: z.ZodString;
        template: z.ZodDefault<z.ZodEnum<{
            landing: "landing";
            "service-index": "service-index";
        }>>;
        sections: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const UniversalSiteSchema: z.ZodObject<{
    schemaVersion: z.ZodNumber;
    slug: z.ZodString;
    vertical: z.ZodString;
    theme: z.ZodObject<{
        name: z.ZodString;
        palette: z.ZodEnum<{
            clinic: "clinic";
            trade: "trade";
            hospitality: "hospitality";
            professional: "professional";
        }>;
        mode: z.ZodDefault<z.ZodEnum<{
            light: "light";
            dark: "dark";
        }>>;
        radius: z.ZodDefault<z.ZodEnum<{
            soft: "soft";
            rounded: "rounded";
            crisp: "crisp";
        }>>;
    }, z.core.$strip>;
    seo: z.ZodObject<{
        title: z.ZodString;
        description: z.ZodString;
        canonicalPath: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    business: z.ZodObject<{
        name: z.ZodString;
        type: z.ZodString;
        tagline: z.ZodString;
        description: z.ZodString;
        phone: z.ZodString;
        email: z.ZodOptional<z.ZodString>;
        address: z.ZodObject<{
            street: z.ZodString;
            city: z.ZodString;
            region: z.ZodString;
            postalCode: z.ZodString;
            country: z.ZodDefault<z.ZodString>;
        }, z.core.$strip>;
        areaServed: z.ZodDefault<z.ZodArray<z.ZodString>>;
        hours: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            value: z.ZodString;
        }, z.core.$strip>>>;
        credentials: z.ZodDefault<z.ZodArray<z.ZodString>>;
        social: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>;
    navigation: z.ZodDefault<z.ZodArray<z.ZodObject<{
        label: z.ZodString;
        href: z.ZodString;
        variant: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            secondary: "secondary";
            text: "text";
        }>>;
    }, z.core.$strip>>>;
    hero: z.ZodObject<{
        eyebrow: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodString;
        primaryCta: z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>;
        secondaryCta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>>;
        mediaAlt: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>;
    sections: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<{
            services: "services";
            proof: "proof";
            process: "process";
            testimonials: "testimonials";
            faq: "faq";
            content: "content";
        }>;
        eyebrow: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        items: z.ZodDefault<z.ZodArray<z.ZodObject<{
            title: z.ZodString;
            description: z.ZodString;
        }, z.core.$strip>>>;
        stats: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            value: z.ZodString;
        }, z.core.$strip>>>;
        steps: z.ZodDefault<z.ZodArray<z.ZodObject<{
            title: z.ZodString;
            description: z.ZodString;
        }, z.core.$strip>>>;
        testimonials: z.ZodDefault<z.ZodArray<z.ZodObject<{
            quote: z.ZodString;
            name: z.ZodString;
            context: z.ZodOptional<z.ZodString>;
        }, z.core.$strip>>>;
        questions: z.ZodDefault<z.ZodArray<z.ZodObject<{
            question: z.ZodString;
            answer: z.ZodString;
        }, z.core.$strip>>>;
        actions: z.ZodDefault<z.ZodArray<z.ZodObject<{
            label: z.ZodString;
            href: z.ZodString;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                text: "text";
            }>>;
        }, z.core.$strip>>>;
    }, z.core.$strip>>;
    ctas: z.ZodOptional<z.ZodObject<{
        final: z.ZodObject<{
            title: z.ZodString;
            summary: z.ZodString;
            actions: z.ZodArray<z.ZodObject<{
                label: z.ZodString;
                href: z.ZodString;
                variant: z.ZodDefault<z.ZodEnum<{
                    primary: "primary";
                    secondary: "secondary";
                    text: "text";
                }>>;
            }, z.core.$strip>>;
        }, z.core.$strip>;
    }, z.core.$strip>>;
    pages: z.ZodArray<z.ZodObject<{
        path: z.ZodString;
        template: z.ZodDefault<z.ZodEnum<{
            landing: "landing";
            "service-index": "service-index";
        }>>;
        sections: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>>;
}, z.core.$strip>;
export declare const websiteSchema: z.ZodObject<{
    schemaVersion: z.ZodDefault<z.ZodString>;
    business: z.ZodObject<{
        name: z.ZodString;
        legalName: z.ZodOptional<z.ZodString>;
        tagline: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        industry: z.ZodOptional<z.ZodString>;
        entityType: z.ZodOptional<z.ZodString>;
        foundedYear: z.ZodOptional<z.ZodNumber>;
        yearsInBusiness: z.ZodOptional<z.ZodNumber>;
        languages: z.ZodDefault<z.ZodArray<z.ZodString>>;
        timezone: z.ZodOptional<z.ZodString>;
        keywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>;
    brand: z.ZodPrefault<z.ZodObject<{
        logo: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        icon: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        colors: z.ZodDefault<z.ZodObject<{
            primary: z.ZodOptional<z.ZodString>;
            secondary: z.ZodOptional<z.ZodString>;
            accent: z.ZodOptional<z.ZodString>;
            background: z.ZodOptional<z.ZodString>;
            foreground: z.ZodOptional<z.ZodString>;
            muted: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        typography: z.ZodDefault<z.ZodObject<{
            headingFont: z.ZodOptional<z.ZodString>;
            bodyFont: z.ZodOptional<z.ZodString>;
            monospaceFont: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        voice: z.ZodPrefault<z.ZodObject<{
            tone: z.ZodOptional<z.ZodString>;
            personality: z.ZodDefault<z.ZodArray<z.ZodString>>;
            writingGuidelines: z.ZodDefault<z.ZodArray<z.ZodString>>;
        }, z.core.$strict>>;
        assets: z.ZodDefault<z.ZodArray<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>;
    contact: z.ZodDefault<z.ZodObject<{
        email: z.ZodOptional<z.ZodString>;
        phone: z.ZodOptional<z.ZodString>;
        smsPhone: z.ZodOptional<z.ZodString>;
        fax: z.ZodOptional<z.ZodString>;
        website: z.ZodOptional<z.ZodString>;
        contactName: z.ZodOptional<z.ZodString>;
        preferredContactMethod: z.ZodOptional<z.ZodEnum<{
            email: "email";
            phone: "phone";
            sms: "sms";
            form: "form";
            appointment: "appointment";
        }>>;
        address: z.ZodOptional<z.ZodObject<{
            street1: z.ZodOptional<z.ZodString>;
            street2: z.ZodOptional<z.ZodString>;
            city: z.ZodOptional<z.ZodString>;
            region: z.ZodOptional<z.ZodString>;
            postalCode: z.ZodOptional<z.ZodString>;
            country: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        mapUrl: z.ZodOptional<z.ZodString>;
        mapEmbedUrl: z.ZodOptional<z.ZodString>;
        emergencyPhone: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    locations: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        address: z.ZodOptional<z.ZodObject<{
            street1: z.ZodOptional<z.ZodString>;
            street2: z.ZodOptional<z.ZodString>;
            city: z.ZodOptional<z.ZodString>;
            region: z.ZodOptional<z.ZodString>;
            postalCode: z.ZodOptional<z.ZodString>;
            country: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        contact: z.ZodDefault<z.ZodObject<{
            email: z.ZodOptional<z.ZodString>;
            phone: z.ZodOptional<z.ZodString>;
            smsPhone: z.ZodOptional<z.ZodString>;
            fax: z.ZodOptional<z.ZodString>;
            website: z.ZodOptional<z.ZodString>;
            contactName: z.ZodOptional<z.ZodString>;
            preferredContactMethod: z.ZodOptional<z.ZodEnum<{
                email: "email";
                phone: "phone";
                sms: "sms";
                form: "form";
                appointment: "appointment";
            }>>;
            address: z.ZodOptional<z.ZodObject<{
                street1: z.ZodOptional<z.ZodString>;
                street2: z.ZodOptional<z.ZodString>;
                city: z.ZodOptional<z.ZodString>;
                region: z.ZodOptional<z.ZodString>;
                postalCode: z.ZodOptional<z.ZodString>;
                country: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            mapUrl: z.ZodOptional<z.ZodString>;
            mapEmbedUrl: z.ZodOptional<z.ZodString>;
            emergencyPhone: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        hours: z.ZodOptional<z.ZodObject<{
            timezone: z.ZodOptional<z.ZodString>;
            summary: z.ZodOptional<z.ZodString>;
            weekly: z.ZodDefault<z.ZodObject<{
                monday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
                tuesday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
                wednesday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
                thursday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
                friday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
                saturday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
                sunday: z.ZodOptional<z.ZodObject<{
                    isClosed: z.ZodDefault<z.ZodBoolean>;
                    ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                        opens: z.ZodString;
                        closes: z.ZodString;
                        label: z.ZodOptional<z.ZodString>;
                    }, z.core.$strict>>>;
                    note: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            holidayHours: z.ZodDefault<z.ZodArray<z.ZodObject<{
                date: z.ZodString;
                name: z.ZodOptional<z.ZodString>;
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
        }, z.core.$strict>>;
        geo: z.ZodOptional<z.ZodObject<{
            latitude: z.ZodNumber;
            longitude: z.ZodNumber;
        }, z.core.$strict>>;
        serviceArea: z.ZodDefault<z.ZodArray<z.ZodString>>;
        amenities: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>>;
    hours: z.ZodPrefault<z.ZodObject<{
        timezone: z.ZodOptional<z.ZodString>;
        summary: z.ZodOptional<z.ZodString>;
        weekly: z.ZodDefault<z.ZodObject<{
            monday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            tuesday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            wednesday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            thursday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            friday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            saturday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
            sunday: z.ZodOptional<z.ZodObject<{
                isClosed: z.ZodDefault<z.ZodBoolean>;
                ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                    opens: z.ZodString;
                    closes: z.ZodString;
                    label: z.ZodOptional<z.ZodString>;
                }, z.core.$strict>>>;
                note: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        holidayHours: z.ZodDefault<z.ZodArray<z.ZodObject<{
            date: z.ZodString;
            name: z.ZodOptional<z.ZodString>;
            isClosed: z.ZodDefault<z.ZodBoolean>;
            ranges: z.ZodDefault<z.ZodArray<z.ZodObject<{
                opens: z.ZodString;
                closes: z.ZodString;
                label: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
            note: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>;
    hero: z.ZodOptional<z.ZodObject<{
        eyebrow: z.ZodOptional<z.ZodString>;
        headline: z.ZodString;
        subheadline: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        primaryCta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
        secondaryCta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        video: z.ZodOptional<z.ZodObject<{
            title: z.ZodString;
            url: z.ZodString;
            provider: z.ZodDefault<z.ZodEnum<{
                youtube: "youtube";
                vimeo: "vimeo";
                "self-hosted": "self-hosted";
                other: "other";
            }>>;
            thumbnail: z.ZodOptional<z.ZodObject<{
                src: z.ZodString;
                alt: z.ZodDefault<z.ZodString>;
                caption: z.ZodOptional<z.ZodString>;
                width: z.ZodOptional<z.ZodNumber>;
                height: z.ZodOptional<z.ZodNumber>;
                focalPoint: z.ZodOptional<z.ZodObject<{
                    x: z.ZodNumber;
                    y: z.ZodNumber;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            transcript: z.ZodOptional<z.ZodString>;
            duration: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        trustSignals: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>;
    about: z.ZodOptional<z.ZodObject<{
        title: z.ZodOptional<z.ZodString>;
        subtitle: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        blocks: z.ZodDefault<z.ZodArray<z.ZodObject<{
            heading: z.ZodOptional<z.ZodString>;
            body: z.ZodOptional<z.ZodString>;
            image: z.ZodOptional<z.ZodObject<{
                src: z.ZodString;
                alt: z.ZodDefault<z.ZodString>;
                caption: z.ZodOptional<z.ZodString>;
                width: z.ZodOptional<z.ZodNumber>;
                height: z.ZodOptional<z.ZodNumber>;
                focalPoint: z.ZodOptional<z.ZodObject<{
                    x: z.ZodNumber;
                    y: z.ZodNumber;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            links: z.ZodDefault<z.ZodArray<z.ZodObject<{
                label: z.ZodString;
                url: z.ZodString;
                ariaLabel: z.ZodOptional<z.ZodString>;
                target: z.ZodDefault<z.ZodEnum<{
                    self: "self";
                    blank: "blank";
                }>>;
                variant: z.ZodDefault<z.ZodEnum<{
                    primary: "primary";
                    secondary: "secondary";
                    tertiary: "tertiary";
                    link: "link";
                    button: "button";
                }>>;
            }, z.core.$strict>>>;
        }, z.core.$strict>>>;
        images: z.ZodDefault<z.ZodArray<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>>;
        cta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    mission: z.ZodOptional<z.ZodObject<{
        title: z.ZodOptional<z.ZodString>;
        subtitle: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        blocks: z.ZodDefault<z.ZodArray<z.ZodObject<{
            heading: z.ZodOptional<z.ZodString>;
            body: z.ZodOptional<z.ZodString>;
            image: z.ZodOptional<z.ZodObject<{
                src: z.ZodString;
                alt: z.ZodDefault<z.ZodString>;
                caption: z.ZodOptional<z.ZodString>;
                width: z.ZodOptional<z.ZodNumber>;
                height: z.ZodOptional<z.ZodNumber>;
                focalPoint: z.ZodOptional<z.ZodObject<{
                    x: z.ZodNumber;
                    y: z.ZodNumber;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            links: z.ZodDefault<z.ZodArray<z.ZodObject<{
                label: z.ZodString;
                url: z.ZodString;
                ariaLabel: z.ZodOptional<z.ZodString>;
                target: z.ZodDefault<z.ZodEnum<{
                    self: "self";
                    blank: "blank";
                }>>;
                variant: z.ZodDefault<z.ZodEnum<{
                    primary: "primary";
                    secondary: "secondary";
                    tertiary: "tertiary";
                    link: "link";
                    button: "button";
                }>>;
            }, z.core.$strict>>>;
        }, z.core.$strict>>>;
        images: z.ZodDefault<z.ZodArray<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>>;
        cta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
    }, z.core.$strict>>;
    services: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        shortDescription: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        category: z.ZodOptional<z.ZodString>;
        price: z.ZodOptional<z.ZodString>;
        duration: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        features: z.ZodDefault<z.ZodArray<z.ZodString>>;
        serviceAreas: z.ZodDefault<z.ZodArray<z.ZodString>>;
        cta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
    products: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        category: z.ZodOptional<z.ZodString>;
        sku: z.ZodOptional<z.ZodString>;
        price: z.ZodOptional<z.ZodString>;
        images: z.ZodDefault<z.ZodArray<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>>;
        features: z.ZodDefault<z.ZodArray<z.ZodString>>;
        available: z.ZodDefault<z.ZodBoolean>;
        cta: z.ZodOptional<z.ZodObject<{
            label: z.ZodString;
            url: z.ZodString;
            ariaLabel: z.ZodOptional<z.ZodString>;
            target: z.ZodDefault<z.ZodEnum<{
                self: "self";
                blank: "blank";
            }>>;
            variant: z.ZodDefault<z.ZodEnum<{
                primary: "primary";
                secondary: "secondary";
                tertiary: "tertiary";
                link: "link";
                button: "button";
            }>>;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
    pricing: z.ZodPrefault<z.ZodObject<{
        title: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        currency: z.ZodOptional<z.ZodString>;
        plans: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodOptional<z.ZodString>;
            name: z.ZodString;
            price: z.ZodString;
            period: z.ZodOptional<z.ZodString>;
            description: z.ZodOptional<z.ZodString>;
            features: z.ZodDefault<z.ZodArray<z.ZodString>>;
            highlighted: z.ZodDefault<z.ZodBoolean>;
            cta: z.ZodOptional<z.ZodObject<{
                label: z.ZodString;
                url: z.ZodString;
                ariaLabel: z.ZodOptional<z.ZodString>;
                target: z.ZodDefault<z.ZodEnum<{
                    self: "self";
                    blank: "blank";
                }>>;
                variant: z.ZodDefault<z.ZodEnum<{
                    primary: "primary";
                    secondary: "secondary";
                    tertiary: "tertiary";
                    link: "link";
                    button: "button";
                }>>;
            }, z.core.$strict>>;
        }, z.core.$strict>>>;
        notes: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>;
    faq: z.ZodDefault<z.ZodArray<z.ZodObject<{
        question: z.ZodString;
        answer: z.ZodString;
        category: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    reviews: z.ZodDefault<z.ZodArray<z.ZodObject<{
        author: z.ZodString;
        quote: z.ZodString;
        rating: z.ZodOptional<z.ZodNumber>;
        source: z.ZodOptional<z.ZodString>;
        date: z.ZodOptional<z.ZodString>;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    testimonials: z.ZodDefault<z.ZodArray<z.ZodObject<{
        author: z.ZodString;
        quote: z.ZodString;
        rating: z.ZodOptional<z.ZodNumber>;
        source: z.ZodOptional<z.ZodString>;
        date: z.ZodOptional<z.ZodString>;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    gallery: z.ZodDefault<z.ZodArray<z.ZodObject<{
        src: z.ZodString;
        alt: z.ZodDefault<z.ZodString>;
        caption: z.ZodOptional<z.ZodString>;
        width: z.ZodOptional<z.ZodNumber>;
        height: z.ZodOptional<z.ZodNumber>;
        focalPoint: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strict>>;
    }, z.core.$strict>>>;
    videos: z.ZodDefault<z.ZodArray<z.ZodObject<{
        title: z.ZodString;
        url: z.ZodString;
        provider: z.ZodDefault<z.ZodEnum<{
            youtube: "youtube";
            vimeo: "vimeo";
            "self-hosted": "self-hosted";
            other: "other";
        }>>;
        thumbnail: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        transcript: z.ZodOptional<z.ZodString>;
        duration: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    team: z.ZodPrefault<z.ZodObject<{
        intro: z.ZodOptional<z.ZodString>;
        members: z.ZodDefault<z.ZodArray<z.ZodObject<{
            name: z.ZodString;
            role: z.ZodOptional<z.ZodString>;
            bio: z.ZodOptional<z.ZodString>;
            photo: z.ZodOptional<z.ZodObject<{
                src: z.ZodString;
                alt: z.ZodDefault<z.ZodString>;
                caption: z.ZodOptional<z.ZodString>;
                width: z.ZodOptional<z.ZodNumber>;
                height: z.ZodOptional<z.ZodNumber>;
                focalPoint: z.ZodOptional<z.ZodObject<{
                    x: z.ZodNumber;
                    y: z.ZodNumber;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            credentials: z.ZodDefault<z.ZodArray<z.ZodString>>;
            socialLinks: z.ZodDefault<z.ZodArray<z.ZodObject<{
                platform: z.ZodString;
                url: z.ZodString;
                handle: z.ZodOptional<z.ZodString>;
            }, z.core.$strict>>>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>;
    careers: z.ZodPrefault<z.ZodObject<{
        intro: z.ZodOptional<z.ZodString>;
        benefits: z.ZodDefault<z.ZodArray<z.ZodString>>;
        openings: z.ZodDefault<z.ZodArray<z.ZodObject<{
            title: z.ZodString;
            location: z.ZodOptional<z.ZodString>;
            type: z.ZodOptional<z.ZodString>;
            description: z.ZodOptional<z.ZodString>;
            requirements: z.ZodDefault<z.ZodArray<z.ZodString>>;
            applyUrl: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>;
    forms: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        title: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        submitLabel: z.ZodDefault<z.ZodString>;
        fields: z.ZodDefault<z.ZodArray<z.ZodObject<{
            name: z.ZodString;
            label: z.ZodString;
            type: z.ZodDefault<z.ZodEnum<{
                number: "number";
                date: "date";
                file: "file";
                email: "email";
                phone: "phone";
                text: "text";
                textarea: "textarea";
                select: "select";
                checkbox: "checkbox";
                radio: "radio";
                time: "time";
            }>>;
            required: z.ZodDefault<z.ZodBoolean>;
            placeholder: z.ZodOptional<z.ZodString>;
            options: z.ZodDefault<z.ZodArray<z.ZodString>>;
            helpText: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
        successMessage: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    appointments: z.ZodPrefault<z.ZodObject<{
        enabled: z.ZodDefault<z.ZodBoolean>;
        bookingUrl: z.ZodOptional<z.ZodString>;
        phone: z.ZodOptional<z.ZodString>;
        appointmentTypes: z.ZodDefault<z.ZodArray<z.ZodString>>;
        leadTime: z.ZodOptional<z.ZodString>;
        cancellationPolicy: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    reservations: z.ZodPrefault<z.ZodObject<{
        enabled: z.ZodDefault<z.ZodBoolean>;
        reservationUrl: z.ZodOptional<z.ZodString>;
        phone: z.ZodOptional<z.ZodString>;
        partySizeMin: z.ZodOptional<z.ZodNumber>;
        partySizeMax: z.ZodOptional<z.ZodNumber>;
        policy: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    menus: z.ZodDefault<z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        sections: z.ZodDefault<z.ZodArray<z.ZodObject<{
            name: z.ZodString;
            description: z.ZodOptional<z.ZodString>;
            items: z.ZodDefault<z.ZodArray<z.ZodObject<{
                name: z.ZodString;
                description: z.ZodOptional<z.ZodString>;
                price: z.ZodOptional<z.ZodString>;
                image: z.ZodOptional<z.ZodObject<{
                    src: z.ZodString;
                    alt: z.ZodDefault<z.ZodString>;
                    caption: z.ZodOptional<z.ZodString>;
                    width: z.ZodOptional<z.ZodNumber>;
                    height: z.ZodOptional<z.ZodNumber>;
                    focalPoint: z.ZodOptional<z.ZodObject<{
                        x: z.ZodNumber;
                        y: z.ZodNumber;
                    }, z.core.$strict>>;
                }, z.core.$strict>>;
                tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
                allergens: z.ZodDefault<z.ZodArray<z.ZodString>>;
                available: z.ZodDefault<z.ZodBoolean>;
            }, z.core.$strict>>>;
        }, z.core.$strict>>>;
    }, z.core.$strict>>>;
    insurance: z.ZodPrefault<z.ZodObject<{
        accepted: z.ZodDefault<z.ZodArray<z.ZodString>>;
        notAccepted: z.ZodDefault<z.ZodArray<z.ZodString>>;
        notes: z.ZodOptional<z.ZodString>;
        verificationUrl: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    specialties: z.ZodDefault<z.ZodArray<z.ZodString>>;
    amenities: z.ZodDefault<z.ZodArray<z.ZodString>>;
    events: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        date: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        url: z.ZodOptional<z.ZodString>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>>;
    news: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        date: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        url: z.ZodOptional<z.ZodString>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>>;
    blog: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        date: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        url: z.ZodOptional<z.ZodString>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>>;
    promotions: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        title: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        body: z.ZodOptional<z.ZodString>;
        date: z.ZodOptional<z.ZodString>;
        image: z.ZodOptional<z.ZodObject<{
            src: z.ZodString;
            alt: z.ZodDefault<z.ZodString>;
            caption: z.ZodOptional<z.ZodString>;
            width: z.ZodOptional<z.ZodNumber>;
            height: z.ZodOptional<z.ZodNumber>;
            focalPoint: z.ZodOptional<z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strict>>;
        }, z.core.$strict>>;
        url: z.ZodOptional<z.ZodString>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
        code: z.ZodOptional<z.ZodString>;
        startsAt: z.ZodOptional<z.ZodString>;
        endsAt: z.ZodOptional<z.ZodString>;
        terms: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    socialLinks: z.ZodDefault<z.ZodArray<z.ZodObject<{
        platform: z.ZodString;
        url: z.ZodString;
        handle: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>>;
    seo: z.ZodPrefault<z.ZodObject<{
        title: z.ZodOptional<z.ZodString>;
        description: z.ZodOptional<z.ZodString>;
        keywords: z.ZodDefault<z.ZodArray<z.ZodString>>;
        canonicalUrl: z.ZodOptional<z.ZodString>;
        noIndex: z.ZodDefault<z.ZodBoolean>;
        openGraph: z.ZodDefault<z.ZodObject<{
            title: z.ZodOptional<z.ZodString>;
            description: z.ZodOptional<z.ZodString>;
            image: z.ZodOptional<z.ZodObject<{
                src: z.ZodString;
                alt: z.ZodDefault<z.ZodString>;
                caption: z.ZodOptional<z.ZodString>;
                width: z.ZodOptional<z.ZodNumber>;
                height: z.ZodOptional<z.ZodNumber>;
                focalPoint: z.ZodOptional<z.ZodObject<{
                    x: z.ZodNumber;
                    y: z.ZodNumber;
                }, z.core.$strict>>;
            }, z.core.$strict>>;
            type: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>;
        structuredData: z.ZodDefault<z.ZodArray<z.ZodRecord<z.ZodString, z.ZodUnknown>>>;
    }, z.core.$strict>>;
    analytics: z.ZodPrefault<z.ZodObject<{
        googleAnalyticsId: z.ZodOptional<z.ZodString>;
        googleTagManagerId: z.ZodOptional<z.ZodString>;
        metaPixelId: z.ZodOptional<z.ZodString>;
        events: z.ZodDefault<z.ZodArray<z.ZodString>>;
        consentRequired: z.ZodDefault<z.ZodBoolean>;
    }, z.core.$strict>>;
    legal: z.ZodPrefault<z.ZodObject<{
        privacyPolicyUrl: z.ZodOptional<z.ZodString>;
        termsUrl: z.ZodOptional<z.ZodString>;
        cookiePolicyUrl: z.ZodOptional<z.ZodString>;
        licenses: z.ZodDefault<z.ZodArray<z.ZodString>>;
        disclaimers: z.ZodDefault<z.ZodArray<z.ZodString>>;
        copyright: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    accessibility: z.ZodPrefault<z.ZodObject<{
        statementUrl: z.ZodOptional<z.ZodString>;
        contactEmail: z.ZodOptional<z.ZodString>;
        contactPhone: z.ZodOptional<z.ZodString>;
        notes: z.ZodOptional<z.ZodString>;
        standards: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strict>>;
    template: z.ZodPrefault<z.ZodObject<{
        id: z.ZodOptional<z.ZodString>;
        name: z.ZodOptional<z.ZodString>;
        variant: z.ZodOptional<z.ZodString>;
        layout: z.ZodOptional<z.ZodString>;
        hiddenSections: z.ZodDefault<z.ZodArray<z.ZodString>>;
        sectionOrder: z.ZodDefault<z.ZodArray<z.ZodString>>;
        options: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, z.core.$strict>>;
    theme: z.ZodPrefault<z.ZodObject<{
        mode: z.ZodDefault<z.ZodEnum<{
            light: "light";
            dark: "dark";
            system: "system";
        }>>;
        radius: z.ZodOptional<z.ZodString>;
        spacing: z.ZodOptional<z.ZodString>;
        colors: z.ZodDefault<z.ZodDefault<z.ZodObject<{
            primary: z.ZodOptional<z.ZodString>;
            secondary: z.ZodOptional<z.ZodString>;
            accent: z.ZodOptional<z.ZodString>;
            background: z.ZodOptional<z.ZodString>;
            foreground: z.ZodOptional<z.ZodString>;
            muted: z.ZodOptional<z.ZodString>;
        }, z.core.$strict>>>;
        customCss: z.ZodOptional<z.ZodString>;
    }, z.core.$strict>>;
    customSections: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, z.core.$strict>;
export type WebsiteData = z.infer<typeof websiteSchema>;
export type WebsiteDataInput = z.input<typeof websiteSchema>;
export type Business = z.infer<typeof businessSchema>;
export type Brand = z.infer<typeof brandSchema>;
export type Contact = z.infer<typeof contactSchema>;
export type Location = z.infer<typeof locationSchema>;
export type Hours = z.infer<typeof hoursSchema>;
export type Hero = z.infer<typeof heroSchema>;
export type ContentSection = z.infer<typeof contentSectionSchema>;
export type Service = z.infer<typeof serviceSchema>;
export type Product = z.infer<typeof productSchema>;
export type Pricing = z.infer<typeof pricingSchema>;
export type FaqItem = z.infer<typeof faqItemSchema>;
export type Review = z.infer<typeof reviewSchema>;
export type TeamMember = z.infer<typeof teamMemberSchema>;
export type Careers = z.infer<typeof careersSchema>;
export type Form = z.infer<typeof formSchema>;
export type Appointments = z.infer<typeof appointmentsSchema>;
export type Reservations = z.infer<typeof reservationsSchema>;
export type Menu = z.infer<typeof menuSchema>;
export type Insurance = z.infer<typeof insuranceSchema>;
export type Promotion = z.infer<typeof promotionSchema>;
export type Seo = z.infer<typeof seoSchema>;
export type Analytics = z.infer<typeof analyticsSchema>;
export type Legal = z.infer<typeof legalSchema>;
export type Accessibility = z.infer<typeof accessibilitySchema>;
export type Template = z.infer<typeof templateSchema>;
export type UniversalSite = z.infer<typeof universalSiteSchema>;
export type UniversalSection = UniversalSite["sections"][number];
export type UniversalAction = z.infer<typeof universalActionSchema>;
export type Theme = z.infer<typeof themeSchema>;
export interface WebsiteValidationIssue {
    readonly code: string;
    readonly message: string;
    readonly path: readonly PropertyKey[];
}
export interface WebsiteValidationErrorOptions {
    readonly issues?: readonly WebsiteValidationIssue[];
    readonly source?: "schema" | "yaml";
    readonly cause?: unknown;
}
export declare class WebsiteValidationError extends Error {
    readonly issues: readonly WebsiteValidationIssue[];
    readonly source: "schema" | "yaml";
    readonly formatted: string;
    constructor(message: string, { issues, source, cause, }?: WebsiteValidationErrorOptions);
}
export type WebsiteValidationResult = {
    readonly success: true;
    readonly data: WebsiteData;
} | {
    readonly success: false;
    readonly error: WebsiteValidationError;
};
export declare function validateWebsiteData(data: unknown): WebsiteData;
export declare function safeValidateWebsiteData(data: unknown): WebsiteValidationResult;
export declare function parseWebsiteYaml(yaml: string): WebsiteData;
export declare function parseUniversalSite(yaml: string, sourcePath?: string): UniversalSite;
export declare function safeParseWebsiteYaml(yaml: string): WebsiteValidationResult;
export declare function formatWebsiteValidationError(error: z.ZodError<unknown>): string;
export declare function formatWebsiteValidationIssues(issues: readonly WebsiteValidationIssue[]): string;
export {};
//# sourceMappingURL=index.d.ts.map